version: "3"
services:
  # Frontend container
  frontend:
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3000
    build: ./frontend
    ports:
      - "3001:3000" # Changed to 3001 to avoid conflict with nginx
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend
    restart: unless-stopped

  # Nginx reverse proxy for friendly startup page
  nginx:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
    restart: unless-stopped

  # Backend API container
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - mongo
    restart: unless-stopped

  # MongoDB container
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

# Define volumes for persistent data
volumes:
  mongo-data:
